[project]
name = "python-solutions"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "basedpyright>=1.28.4",
    "pytest>=8.3.5",
    "ruff>=0.11.2",
]
